const MOUSE_CLICK = 'MOUSE_CLICK';
const SCAN_PAGE = 'SCAN_PAGE';
const GET_QUIZZES = 'GET_QUIZZES';
const FIND_QUESTION = 'FIND_QUESTION';
const FIND_ANSWER = 'FIND_ANSWER';
const PICK_ANSWER = 'PICK_ANSWER';

module.exports = {
  MOUSE_CLICK,
  SCAN_PAGE,
  GET_QUIZZES,
  FIND_QUESTION,
  FIND_ANSWER,
  PICK_ANSWER,
}
